# Generated by Django 4.2.5 on 2023-10-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'permissions': [('operator', 'Can add ticket,change, change yourself profile'), ('master', 'Can closed ticked,change owner, change yourself profile')]},
        ),
    ]
