# Generated by Django 4.2.5 on 2023-09-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Ticket',
        ),
    ]
