# Generated by Django 4.2.5 on 2023-10-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
