# Generated by Django 4.2.5 on 2023-09-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_rename_human_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.district', verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.street', verbose_name='street')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='house',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='tester.house', verbose_name='house'),
            preserve_default=False,
        ),
    ]
