# Generated by Django 4.2.5 on 2023-09-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_human_ticket_closed_date_ticket_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='name',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='permissions',
            field=models.CharField(choices=[('operator', 'Оператор'), ('models', 'Мастер'), ('admin', 'Воспитатель'), ('god', 'Боженька🌕'), (None, 'Никто')], default=None, max_length=32, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment_master',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий мастера'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment_operator',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий оператора'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(max_length=32, verbose_name='имя пользователя'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='имя')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.house', verbose_name='home')),
            ],
        ),
    ]
