# Generated by Django 4.2.5 on 2023-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open'),
        ),
    ]
