# Generated by Django 4.2.5 on 2023-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(choices=[(True, 'Открыта'), (False, 'Закрыта')], default=True),
        ),
    ]
