# Generated by Django 4.2.5 on 2023-09-29 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_human_name_human_permissions_ticket_comment_master_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Задрот', 'verbose_name_plural': 'Задроты'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='street_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Альтернативная улица'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='permissions',
            field=models.CharField(choices=[('operator', 'Оператор📞'), ('models', 'Мастер🛠'), ('admin', 'Воспитатель👶'), ('god', 'Боженька🧬'), (None, 'Никто')], default=None, max_length=32, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='human',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='Кликуха'),
        ),
    ]
