# Generated by Django 4.2.5 on 2023-09-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_ticket_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='street',
        ),
    ]
