# Generated by Django 4.2.5 on 2023-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0010_remove_ticket_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=53)),
            ],
        ),
    ]
