# Generated by Django 4.2.5 on 2023-09-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0011_h'),
    ]

    operations = [
        migrations.DeleteModel(
            name='H',
        ),
    ]
