# Generated by Django 4.2.5 on 2023-09-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_alter_ticket_options_remove_ticket_street_custom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.house', verbose_name='Дом'),
        ),
    ]
