# Generated by Django 4.2.5 on 2023-09-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_alter_ticket_options_remove_apartment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='apartment',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.apartment', verbose_name='Квартира'),
        ),
    ]
