# Generated by Django 4.2.5 on 2023-09-30 08:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0015_ticket_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='Street.district', chained_model_field='Street.district', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
