# Generated by Django 4.2.5 on 2023-09-30 08:54

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0017_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x000001EEC2BF7250>', chained_model_field='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x000001EEC2BF7250>', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
    ]
