# Generated by Django 4.2.5 on 2023-11-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0017_historicalticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=25, verbose_name='Текст')),
            ],
        ),
    ]
