# Generated by Django 4.2.5 on 2023-11-07 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0018_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
    ]
