# Generated by Django 4.2.5 on 2023-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0019_news_date_alter_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Заголовок'),
        ),
    ]
