# Generated by Django 4.2.5 on 2023-09-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0022_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='street',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street', verbose_name='Улица'),
        ),
    ]
