# Generated by Django 4.2.5 on 2023-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0025_alter_news_options_alter_historicalticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Открыта'), (False, 'Закрыта'), (None, 'В обработке')], default=None, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Открыта'), (False, 'Закрыта'), (None, 'В обработке')], default=None, null=True, verbose_name='Статус'),
        ),
    ]
