# Generated by Django 4.2.5 on 2023-11-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0026_alter_historicalticket_status_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='update',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='update',
        ),
    ]
