# Generated by Django 4.2.5 on 2023-10-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0026_human_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='name',
        ),
        migrations.RemoveField(
            model_name='human',
            name='user_name',
        ),
    ]
