# Generated by Django 4.2.5 on 2023-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0027_remove_historicalticket_update_remove_ticket_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил '),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил '),
        ),
    ]
