# Generated by Django 4.2.5 on 2023-10-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0027_remove_human_name_remove_human_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='user',
        ),
        migrations.AddField(
            model_name='human',
            name='name',
            field=models.CharField(default=None, max_length=32, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='user_name',
            field=models.CharField(default=None, max_length=32, verbose_name='Кликуха'),
            preserve_default=False,
        ),
    ]
