# Generated by Django 4.2.5 on 2023-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0028_remove_human_user_human_name_human_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartment',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Квартира'),
        ),
    ]
