# Generated by Django 4.2.5 on 2023-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0029_alter_historicalticket_user_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил '),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил '),
        ),
    ]
