# Generated by Django 4.2.5 on 2023-10-01 21:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0030_ticket_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='name', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.district'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='name', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
    ]
