# Generated by Django 4.2.5 on 2023-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0030_alter_historicalticket_user_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл отключки')),
            ],
        ),
    ]
