# Generated by Django 4.2.5 on 2023-11-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0032_alter_user_options_alter_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, 'Выполнена'), (False, 'Не дозвон'), (None, 'Отказ')], default=True, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, 'Выполнена'), (False, 'Не дозвон'), (None, 'Отказ')], default=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Изменил'),
        ),
    ]
