# Generated by Django 4.2.5 on 2023-10-01 21:51

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0032_alter_region_name_alter_ticket_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.district', view_name='Район'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street', view_name='Улица'),
        ),
    ]
