# Generated by Django 4.2.5 on 2023-10-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0033_alter_ticket_district_alter_ticket_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='district',
        ),
    ]
