# Generated by Django 4.2.5 on 2023-11-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0034_alter_historicalticket_cause_alter_ticket_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, 'Выполнена'), (False, 'Не дозвон'), (None, '----')], default=None, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, 'Выполнена'), (False, 'Не дозвон'), (None, '----')], default=None, null=True, verbose_name='Причина'),
        ),
    ]
