# Generated by Django 4.2.5 on 2023-10-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0035_ticket_district_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Регион'),
        ),
    ]
