# Generated by Django 4.2.5 on 2023-10-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0036_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='operator',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
