# Generated by Django 4.2.5 on 2023-10-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0037_ticket_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='username',
        ),
    ]
