# Generated by Django 4.2.5 on 2023-10-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0039_tickettype_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[(None, 'Открыта'), ('warning', 'Просрочена'), ('close', 'Закрыта')], default=None, max_length=13, verbose_name='Тип заявки'),
        ),
    ]
