# Generated by Django 4.2.5 on 2023-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0040_alter_tickettype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение')], max_length=13, verbose_name='Тип заявки'),
        ),
    ]
