# Generated by Django 4.2.5 on 2023-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0040_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, '----------'), (None, 'Выполнена'), (False, 'Не дозвон')], default=None, null=True, verbose_name='Причина закрытия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, '----------'), (None, 'Выполнена'), (False, 'Не дозвон')], default=None, null=True, verbose_name='Причина закрытия'),
        ),
    ]
