# Generated by Django 4.2.5 on 2023-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0041_alter_historicalticket_cause_alter_ticket_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Открыта'), (False, 'Закрыта')], default=True, null=True, verbose_name='Статус_deleted'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Открыта'), (False, 'Закрыта')], default=True, null=True, verbose_name='Статус_deleted'),
        ),
    ]
