# Generated by Django 4.2.5 on 2023-10-01 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0041_alter_tickettype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='user_name',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение')], default=None, max_length=13, verbose_name='Тип заявки'),
        ),
    ]
