# Generated by Django 4.2.5 on 2023-10-01 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0042_alter_human_user_name_alter_tickettype_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Person',
        ),
    ]
