# Generated by Django 4.2.5 on 2023-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0042_historicalticket_deleted_ticket_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(False, 'Закрыта'), (True, 'Открыта')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(False, 'Закрыта'), (True, 'Открыта')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
    ]
