# Generated by Django 4.2.5 on 2023-12-04 04:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0044_alter_historicalticket_deleted_alter_ticket_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
