# Generated by Django 4.2.5 on 2023-12-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0045_alter_ticket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='deleted',
        ),
    ]
