# Generated by Django 4.2.5 on 2023-10-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0045_remove_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='permissions',
            field=models.CharField(choices=[('operator', 'Оператор📞'), ('master', 'Мастер🛠'), ('admin', 'Воспитатель👶'), ('god', 'Боженька🧬'), (None, 'Никто')], default=None, max_length=32, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operator',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tester.person', verbose_name='Оператор'),
        ),
    ]
