# Generated by Django 4.2.5 on 2023-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0046_alter_ticket_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Закрыта'), (False, 'Открыта')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Закрыта'), (False, 'Открыта')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
    ]
