# Generated by Django 4.2.5 on 2023-10-02 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0046_alter_person_permissions_alter_ticket_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
