# Generated by Django 4.2.5 on 2023-10-02 19:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0047_alter_person_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='regoin',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='name', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='tester.region'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='tester.district'),
        ),
    ]
