# Generated by Django 4.2.5 on 2023-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0047_historicalticket_deleted_ticket_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Удаленна'), (False, 'Активна')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(blank=True, choices=[(True, 'Удаленна'), (False, 'Активна')], default=False, null=True, verbose_name='Статус_deleted'),
        ),
    ]
