# Generated by Django 4.2.5 on 2023-12-11 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0048_alter_historicalticket_deleted_alter_ticket_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mater_shutdown', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
    ]
