# Generated by Django 4.2.5 on 2023-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0049_rename_regoin_ticket_region_alter_ticket_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='region',
        ),
    ]
