# Generated by Django 4.2.5 on 2023-10-02 19:13

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0050_remove_ticket_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='house',
            field=models.CharField(max_length=16, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='name', chained_model_field='apartment', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
    ]
