# Generated by Django 4.2.5 on 2023-10-02 19:24

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0051_alter_ticket_house_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tester.district'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='name', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
    ]
