# Generated by Django 4.2.5 on 2023-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0051_alter_historicalticket_street_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Кв'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Кв'),
        ),
    ]
