# Generated by Django 4.2.5 on 2023-12-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0052_alter_historicalticket_apartment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTicket',
        ),
    ]
