# Generated by Django 4.2.5 on 2023-12-29 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0053_delete_historicalticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shutdown',
            options={'verbose_name': 'Отключки', 'verbose_name_plural': 'Отключки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'permissions': [('operator', 'Can add ticket, change, change yourself profile'), ('master', 'Can closed ticked, change owner, change yourself profile'), ('dispatcher', 'Can add ticket, change, change yourself profile, add news, change news, change ticket status')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='shutdown',
            name='apartment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Кв'),
        ),
        migrations.AddField(
            model_name='shutdown',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='shutdown',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата открытия'),
        ),
        migrations.AddField(
            model_name='shutdown',
            name='date_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата измененя'),
        ),
        migrations.AddField(
            model_name='shutdown',
            name='house',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='shutdown',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Улица'),
        ),
    ]
