# Generated by Django 4.2.5 on 2024-01-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0054_alter_shutdown_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='completion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выполнение'),
        ),
    ]
