# Generated by Django 4.2.5 on 2024-01-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0056_alter_shutdown_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='telegram_id'),
        ),
    ]
