# Generated by Django 4.2.5 on 2023-10-02 19:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0057_alter_ticket_district_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tester.district', verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='district', chained_model_field='district', default=None, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
            preserve_default=False,
        ),
    ]
