# Generated by Django 4.2.5 on 2024-01-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0059_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='completion_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_change',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Изменил'),
        ),
    ]
