# Generated by Django 4.2.5 on 2024-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0060_remove_ticket_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
