# Generated by Django 4.2.5 on 2024-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0061_ticket_completion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'permissions': [('operator', 'Can add ticket, change, change yourself profile'), ('master', 'Can closed ticked, change owner, change yourself profile'), ('dispatcher', 'Can add ticket, change, change yourself profile, add news, change news, change ticket status')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Ремонт', 'Ремонт'), ('Настройка', 'Настройка'), ('Перенос', 'Перенос'), ('Включение', 'Включение'), ('Отключение', 'Отключение'), ('Установка', 'Установка')], max_length=13, verbose_name='Тип заявки'),
        ),
    ]
