# Generated by Django 4.2.5 on 2024-01-22 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0062_alter_user_options_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='master',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='mater_shutdown', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
            preserve_default=False,
        ),
    ]
