# Generated by Django 4.2.5 on 2024-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0064_shutdown_comment_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cause',
            field=models.BooleanField(blank=True, choices=[(True, '----------'), (None, 'Выполнена'), (False, 'Недозвон')], default=None, null=True, verbose_name='Причина закрытия'),
        ),
    ]
