# Generated by Django 4.2.5 on 2023-10-02 21:37

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0066_alter_ticket_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='street',
        ),
        migrations.AddField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='district', chained_model_field='district', to='tester.street'),
        ),
    ]
