# Generated by Django 4.2.5 on 2023-10-02 21:38

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0067_remove_ticket_street_ticket_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='street',
        ),
        migrations.AddField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='district', chained_model_field='district', default=None, on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
            preserve_default=False,
        ),
    ]
