# Generated by Django 4.2.5 on 2023-10-02 21:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0069_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, to='tester.street'),
        ),
    ]
