# Generated by Django 4.2.5 on 2023-10-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0070_alter_ticket_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tester.tickettype', verbose_name='Тип заявки'),
        ),
    ]
