# Generated by Django 4.2.5 on 2023-10-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0075_alter_person_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='identify',
        ),
    ]
