# Generated by Django 4.2.5 on 2023-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0076_remove_ticket_identify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение'), ('installation', 'Установка')], default='repair', max_length=32, verbose_name='Тип заявки'),
        ),
    ]
