# Generated by Django 4.2.5 on 2023-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0077_alter_tickettype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(max_length=32, verbose_name='Тип заявки'),
        ),
    ]
