# Generated by Django 4.2.5 on 2023-10-03 14:47

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0079_alter_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение'), ('installation', 'Установка')], default='repair', max_length=32, verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, null=True, to='tester.tickettype', verbose_name='Тип заявки'),
        ),
    ]
