# Generated by Django 4.2.5 on 2023-10-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0086_alter_ticket_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('sex', 'sex'), ('close_task', 'Can remove a task by setting its status as closed')], 'verbose_name': 'Задрот', 'verbose_name_plural': 'Задроты'},
        ),
    ]
