# Generated by Django 4.2.5 on 2023-10-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0087_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('operator', 'Can add ticket,change, change yourself profile'), ('master', 'Can closed ticked,change owner, change yourself profile')], 'verbose_name': 'Задрот', 'verbose_name_plural': 'Задроты'},
        ),
    ]
