# Generated by Django 4.2.5 on 2023-10-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0088_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[(True, 'New'), (False, 'Old')], default=None, max_length=32, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='permissions',
            field=models.CharField(blank=True, choices=[('operator', 'Оператор📞'), ('master', 'Мастер🛠'), ('admin', 'Воспитатель👶'), ('god', 'Боженька🧬'), (None, 'Никто')], default=None, max_length=32, null=True, verbose_name='Роль'),
        ),
    ]
