# Generated by Django 4.2.5 on 2023-10-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0091_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'New'), ('Уже в базе', 'Old')], default=None, max_length=32, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.CharField(blank=True, default='repair', max_length=32, null=True, verbose_name='Тип заявки'),
        ),
    ]
