# Generated by Django 4.2.5 on 2023-10-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0096_alter_tickettype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='type',
        ),
    ]
