# Generated by Django 4.2.5 on 2023-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0098_tickettype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Тип заявки'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('None', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение'), ('installation', 'Установка')], default='None', max_length=32, null=True, verbose_name='Тип заявки'),
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
