# Generated by Django 4.2.5 on 2023-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0099_alter_house_options_alter_ticket_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('None', 'Ремонт'), ('settings', 'Настройка'), ('transfer', 'Перенос'), ('shutdown', 'Отключение'), ('installation', 'Установка')], default='None', max_length=32, verbose_name='Тип заявки'),
        ),
    ]
