# Generated by Django 4.2.5 on 2023-10-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0101_alter_ticket_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='operator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='tester.person', verbose_name='Оператор'),
        ),
    ]
